platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5'
pod 'AXRatingView'
pod 'ChameleonFramework'
pod 'DoActionSheet'
pod 'JVFloatLabeledTextField'
pod 'KVNProgress'
pod 'MCSwipeTableViewCell'
pod 'Onboard'
pod 'RKDropdownAlert'
pod 'UIView+Positioning'
pod 'XLForm'
