workspace 'joyyios.xcworkspace'
xcodeproj 'joyyios.xcodeproj'

platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5'
pod 'ChameleonFramework'
pod 'FDFullscreenPopGesture'
pod 'JSQMessagesViewController'
pod 'JVFloatLabeledTextField'
pod 'KVNProgress'
pod 'KVOController'
pod 'MJRefresh'
pod 'MSWeakTimer'
pod 'Onboard'
pod 'RKDropdownAlert'
pod 'SlackTextViewController'
pod 'TTTAttributedLabel'
pod 'UIView+Positioning'
pod 'XMPPFramework'
pod 'YTKKeyValueStore'
