workspace 'joyyios.xcworkspace'
xcodeproj 'joyyios.xcodeproj'

platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5'
pod 'AFNetworking-Synchronous/2.x'
pod 'AWSCore'
pod 'AWSS3'
pod 'ChameleonFramework'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FDFullscreenPopGesture'
pod 'JSQMessagesViewController'
pod 'JVFloatLabeledTextField'
pod 'KVNProgress'
pod 'KVOController'
pod 'MJRefresh'
pod 'MSWeakTimer'
pod 'Onboard'
pod 'RKDropdownAlert'
pod 'SlackTextViewController'
pod 'TTTAttributedLabel'
pod 'UICKeyChainStore'
pod 'UIView+Positioning'
pod 'VMaskTextField'
pod 'XMPPFramework', '3.6.5'
pod 'YTKKeyValueStore'
