CREATE TABLE creditcards (
    id                  BIGSERIAL  PRIMARY KEY,
    user_id             BIGINT        NOT NULL,  -- the id of the user who own this card
    number_last_4       CHAR(4)       NOT NULL,  -- the last 4 digits of the credit card number
    stripe_customer_id  TEXT          NOT NULL,  -- the customer.id generated by the stripe from the one-time stripe token
    expiry_month        SMALLINT      NOT NULL,
    expiry_year         SMALLINT      NOT NULL,
    card_type           SMALLINT      NOT NULL,  -- see below 
    created_at          TIMESTAMPTZ   NOT NULL,
    updated_at          TIMESTAMPTZ   NOT NULL,
    deleted             BOOLEAN       NOT NULL DEFAULT false,

    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX creditcards_user_id_index ON creditcards (user_id);



/* card_type
typedef NS_ENUM(NSInteger, JYCreditCardType)
{
    JYCreditCardTypeUnrecognized = 0, // The card number does not correspond to any recognizable card type.
    JYCreditCardTypeAmbiguous = 1,    // The card number corresponds to multiple card types
    JYCreditCardTypeAmex = '3',       // American Express
    JYCreditCardTypeJCB = 'J',        // Japan Credit Bureau
    JYCreditCardTypeVisa = '4',       // VISA
    JYCreditCardTypeMastercard = '5', // MasterCard
    JYCreditCardTypeDiscover = '6'    // Discover Card
};
*/