CREATE TABLE creditcards (
    id                  BIGSERIAL  PRIMARY KEY,
    user_id             BIGINT        NOT NULL,  -- the id of the user who own this card
    number_last_4       CHAR(4)       NOT NULL,  -- the last 4 digits of the credit card number
    stripe_customer_id  TEXT          NOT NULL,  -- the customer.id generated by the stripe from the one-time stripe token
    expire_month        SMALLINT      NOT NULL,
    expire_year         SMALLINT      NOT NULL,
    created_at          TIMESTAMPTZ   NOT NULL,
    updated_at          TIMESTAMPTZ   NOT NULL,
    deleted             BOOLEAN       NOT NULL DEFAULT false,

    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX creditcards_user_id_index ON creditcards (user_id);

